name: Code Analysis

on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install cloc and jscpd
      run: |
        sudo apt-get install -y cloc
        npm install -g jscpd

    - name: Count lines of code with cloc
      run: |
        cloc .

    - name: Detect duplicate code with jscpd
      run: |
        jscpd --path . --reporters json --output jscpd-report.json

    - name: Upload duplicate code report
      uses: actions/upload-artifact@v3
      with:
        name: jscpd-report
        path: jscpd-report.json
